sudo: true
language: cpp
compiler:
 - g++-4.8
before_install:
 # What is the current file size max for core files?
 # It is usually 0, which means no core file will be dumped if there is a crash 
 - ulimit -c
 - ulimit -a -S
 - ulimit -a -H
 - cat /proc/sys/kernel/core_pattern
 - cat /etc/default/apport
 - service --status-all || true
 - initctl list || true
script: 
       # install mason
       - mkdir ./mason/
       - curl -sSfL https://github.com/mapbox/mason/archive/v0.2.0.tar.gz | tar --gunzip --extract --strip-components=1 --directory=./mason/
       # install gdb via mason
       - ./mason/mason install gdb 7.12
       # put GDB on PATH
       - export PATH=$(./mason/mason prefix gdb 7.12)/bin:${PATH}
       # install logbt
       - curl -sSfL https://github.com/mapbox/logbt/archive/v1.6.0.tar.gz | tar --gunzip --extract --strip-components=2 --exclude="*md" --exclude="test*" --directory=.
       - RESULT=0
       - cd tests && make 
       - sudo bash -c "echo '/tmp/logbt-coredumps/core.%p.%E' > /proc/sys/kernel/core_pattern"
       - cd tests && make test
       - if [[ ${RESULT} != 139 ]]; then echo "expected segfault and 139 exit but instead exited with ${RESULT}" && exit 1; fi;
os:
  - linux
